# Generated by Django 6.0.3 on 2026-05-09 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_organizationsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOrgMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(db_index=True)),
                ('org_timezone_at_snapshot', models.CharField(max_length=64)),
                ('metrics_schema_version', models.PositiveIntegerField(default=1)),
                ('lifecycle_state', models.CharField(choices=[('provisional', 'Provisional — inside mutation window'), ('frozen', 'Frozen — past mutation window'), ('rebuilt', 'Rebuilt — was frozen, then forcibly rewritten'), ('corrupt', 'Corrupt — anchor inconsistency detected; excluded from charts')], default='provisional', max_length=16)),
                ('built_at', models.DateTimeField(auto_now=True)),
                ('revenue_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('revenue_accrual', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('invoices_paid_count', models.PositiveIntegerField(default=0)),
                ('appointments_total', models.PositiveIntegerField(default=0)),
                ('appointments_done', models.PositiveIntegerField(default=0)),
                ('appointments_no_show', models.PositiveIntegerField(default=0)),
                ('medical_records_closed', models.PositiveIntegerField(default=0)),
                ('excluded_anchor_missing', models.PositiveIntegerField(default=0, help_text='Rows skipped because their analytics anchor was NULL. Should be zero post-Capa 1 CHECK constraints; non-zero = bug or imported data that bypassed the writer.')),
                ('build_warnings_count', models.PositiveIntegerField(default=0)),
                ('provenance_mix', models.JSONField(blank=True, default=dict, help_text="Per-anchor source breakdown for rows that fed this snapshot, e.g. {'paid_at': {'service': 921, 'fallback': 2}}. Lets the trust score for the snapshot day be reconstructed without re-querying the source tables.")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['organization', '-date'], name='idx_dom_org_date'), models.Index(fields=['organization', 'lifecycle_state'], name='idx_dom_org_lifecycle')],
                'unique_together': {('organization', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DashboardSnapshotAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('snapshot_date', models.DateField()),
                ('from_state', models.CharField(blank=True, max_length=16)),
                ('to_state', models.CharField(blank=True, max_length=16)),
                ('kind', models.CharField(choices=[('build', 'Snapshot built (initial or normal nightly)'), ('skip_frozen', 'Skipped because row was frozen'), ('rebuild', 'Forced rebuild via --force'), ('freeze', 'Lifecycle transitioned to frozen'), ('corruption_detected', 'Marked corrupt due to anchor inconsistency'), ('late_arrival_rebuild', 'Rebuild triggered by late-arriving event')], max_length=32)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('triggered_by_system', models.BooleanField(default=True, help_text='False when a human user triggered (e.g. mgmt command run with --user).')),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='organizations.organization')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'snapshot_date', '-created_at'], name='idx_dsa_org_date_created')],
            },
        ),
    ]
