# Generated by Django 6.0.3 on 2026-04-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('medication', 'Medicamento'), ('food', 'Alimento'), ('accessory', 'Accesorio'), ('other', 'Otro')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_prescription',
            field=models.BooleanField(default=False),
        ),
    ]
