# Generated by Django 6.0.3 on 2026-04-10 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_finalize_inventory_restructure'),
        ('organizations', '0002_organization_timezone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization'),
        ),
    ]
