# Generated by Django 6.0.3 on 2026-04-13 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoiceitem_presentation_alter_invoice_status_and_more'),
        ('inventory', '0009_alter_presentation_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='billing.invoice'),
        ),
    ]
