# Generated by Django 6.0.3 on 2026-04-15 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_medicalrecordproduct_created_at_and_more'),
        ('organizations', '0003_organization_tax_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='presentation',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='presentation_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='presentation',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__gt', 0)), name='presentation_sale_price_positive'),
        ),
    ]
