# Generated by Django 6.0.3 on 2026-04-28 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_presentation_presentation_stock_non_negative_and_more'),
        ('organizations', '0005_organizationsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'ordering': ['product__name', 'name']},
        ),
        migrations.AlterField(
            model_name='presentation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='inventory.product'),
        ),
        migrations.AlterUniqueTogether(
            name='presentation',
            unique_together={('product', 'name')},
        ),
        migrations.AddIndex(
            model_name='presentation',
            index=models.Index(fields=['product'], name='inventory_p_product_3223d8_idx'),
        ),
        migrations.AddIndex(
            model_name='presentation',
            index=models.Index(fields=['stock'], name='inventory_p_stock_97d467_idx'),
        ),
    ]
