# Generated by Django 6.0.3 on 2026-05-09 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_invoice_idx_inv_org_status_paid_and_more'),
        ('inventory', '0014_add_public_id_to_exposed_models'),
        ('medical_records', '0015_medicalrecord_closed_at_provenance'),
        ('organizations', '0005_organizationsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'presentation', '-created_at'], name='idx_stockmov_org_pres_created'),
        ),
    ]
