# Generated by Django 6.0.3 on 2026-04-15 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_appointment_organiz_abc1ec_idx'),
        ('medical_records', '0004_medicalrecord_created_by_medicalrecord_is_active_and_more'),
        ('organizations', '0003_organization_tax_rate'),
        ('patients', '0005_owner_created_at_owner_created_by_owner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['organization', 'pet', '-created_at'], name='medical_rec_organiz_12d8fd_idx'),
        ),
    ]
