# Generated by Django 6.0.3 on 2026-04-25 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0005_medicalrecord_medical_rec_organiz_12d8fd_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_medical_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="status",
            field=models.CharField(
                choices=[("open", "Abierta"), ("closed", "Cerrada")],
                db_index=True,
                default="open",
                max_length=10,
            ),
        ),
    ]
