# Generated by Django 6.0.3 on 2026-05-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0010_add_public_id_to_exposed_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='notes',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='treatment',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
