# Generated by Django 6.0.3 on 2026-05-09 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_appointment_idx_appt_org_start_status'),
        ('medical_records', '0015_medicalrecord_closed_at_provenance'),
        ('organizations', '0005_organizationsettings'),
        ('patients', '0010_unique_generic_pet_per_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vitalsigns',
            new_name='medical_rec_medical_a94e83_idx',
            old_name='medical_rec_medical_9efa5c_idx',
        ),
        migrations.RenameIndex(
            model_name='vitalsigns',
            new_name='medical_rec_recorde_487581_idx',
            old_name='medical_rec_recorde_f2a8b1_idx',
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['organization', 'status', '-closed_at'], name='idx_mr_org_status_closed_at'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['organization', 'appointment'], name='idx_mr_org_appointment'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='idx_mr_org_status_created'),
        ),
        migrations.AddIndex(
            model_name='vaccinerecord',
            index=models.Index(fields=['organization', 'application_date'], name='idx_vacc_org_app_date'),
        ),
        migrations.AddIndex(
            model_name='vaccinerecord',
            index=models.Index(fields=['organization', 'next_due_date'], name='idx_vacc_org_next_due'),
        ),
    ]
