# Generated by Django 6.0.3 on 2026-05-17 19:32
#
# PR-4B — Issue #11 / ADR p15+p16 (cascade lockdown día 4).
# Cambios: MedicalRecord.pet y VaccineRecord.pet on_delete CASCADE → PROTECT.
# Razón: borrar un Pet eliminaba todo su expediente clínico (consultas +
# registros vacunales). Violación NOM-046 (retención 5 años) + NOM-007
# (registros de vacunación). PROTECT preserva integridad referencial.
#
# Acoplamiento downstream:
# - Pet.owner ya es PROTECT (patients/0011) → un Pet con historial nunca
#   se borra vía cascade desde Owner.
# - Dos AlterField en un solo Migration atómicamente — Django los ejecuta
#   en orden secuencial dentro de la misma transacción.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0016_rename_medical_rec_medical_9efa5c_idx_medical_rec_medical_a94e83_idx_and_more'),
        ('patients', '0011_alter_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='patients.pet'),
        ),
        migrations.AlterField(
            model_name='vaccinerecord',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccine_records', to='patients.pet'),
        ),
    ]
