import {
    Stethoscope, LayoutDashboard, PawPrint, CalendarClock, FileHeart,
    Package, Receipt, Users, Settings, LogOut,
    X, Search, Grid3x3, List, User, Phone,
    Syringe, TrendingUp, TrendingDown, Pencil, Trash2, ChevronRight,
    AlertTriangle, Dog, Cat, Bone, Box,
    ArrowUpDown, ArrowUp, ArrowDown,
    Calendar, CalendarDays,
    Plus, Minus, Edit2, Edit3,
    ChevronLeft, ChevronDown, ChevronUp,
    FileText, Pill, ShoppingBag,
    Clock, Check, CheckCircle,
    AlertCircle, AlertOctagon,
    Info, HelpCircle,
    Eye, EyeOff,
    Filter as FilterIconLucide, SlidersHorizontal,
    RefreshCw, Loader2,
    Printer, Download, Upload,
    Frown,
} from "lucide-react";

export const Icon = {
    Stethoscope: ({ s = 20, c = "currentColor" }) => <Stethoscope size={s} color={c} strokeWidth={2} />,
    LayoutDashboard: ({ s = 20, c = "currentColor" }) => <LayoutDashboard size={s} color={c} strokeWidth={2} />,
    PawPrint: ({ s = 20, c = "currentColor" }) => <PawPrint size={s} color={c} strokeWidth={2} />,
    CalendarClock: ({ s = 20, c = "currentColor" }) => <CalendarClock size={s} color={c} strokeWidth={2} />,
    FileHeart: ({ s = 20, c = "currentColor" }) => <FileHeart size={s} color={c} strokeWidth={2} />,
    Package: ({ s = 20, c = "currentColor" }) => <Package size={s} color={c} strokeWidth={2} />,
    Receipt: ({ s = 20, c = "currentColor" }) => <Receipt size={s} color={c} strokeWidth={2} />,
    Users: ({ s = 20, c = "currentColor" }) => <Users size={s} color={c} strokeWidth={2} />,
    Settings: ({ s = 20, c = "currentColor" }) => <Settings size={s} color={c} strokeWidth={2} />,
    LogOut: ({ s = 20, c = "currentColor" }) => <LogOut size={s} color={c} strokeWidth={2} />,

    X: ({ s = 20, c = "currentColor" }) => <X size={s} color={c} strokeWidth={2} />,
    Search: ({ s = 20, c = "currentColor" }) => <Search size={s} color={c} strokeWidth={2} />,
    Grid: ({ s = 20, c = "currentColor" }) => <Grid3x3 size={s} color={c} strokeWidth={2} />,
    Rows: ({ s = 20, c = "currentColor" }) => <List size={s} color={c} strokeWidth={2} />,
    User: ({ s = 20, c = "currentColor" }) => <User size={s} color={c} strokeWidth={2} />,
    Phone: ({ s = 20, c = "currentColor" }) => <Phone size={s} color={c} strokeWidth={2} />,
    Syringe: ({ s = 20, c = "currentColor" }) => <Syringe size={s} color={c} strokeWidth={2} />,
    TrendUp: ({ s = 20, c = "currentColor" }) => <TrendingUp size={s} color={c} strokeWidth={2} />,
    Edit: ({ s = 20, c = "currentColor" }) => <Edit2 size={s} color={c} strokeWidth={2} />,
    Edit2: ({ s = 20, c = "currentColor" }) => <Edit3 size={s} color={c} strokeWidth={2} />,
    Trash: ({ s = 20, c = "currentColor" }) => <Trash2 size={s} color={c} strokeWidth={2} />,
    ChevronRight: ({ s = 20, c = "currentColor" }) => <ChevronRight size={s} color={c} strokeWidth={2} />,
    ChevronLeft: ({ s = 20, c = "currentColor" }) => <ChevronLeft size={s} color={c} strokeWidth={2} />,
    ChevronDown: ({ s = 20, c = "currentColor" }) => <ChevronDown size={s} color={c} strokeWidth={2} />,
    ChevronUp: ({ s = 20, c = "currentColor" }) => <ChevronUp size={s} color={c} strokeWidth={2} />,
    AlertTriangle: ({ s = 20, c = "currentColor" }) => <AlertTriangle size={s} color={c} strokeWidth={2} />,
    AlertCircle: ({ s = 20, c = "currentColor" }) => <AlertCircle size={s} color={c} strokeWidth={2} />,
    AlertOctagon: ({ s = 20, c = "currentColor" }) => <AlertOctagon size={s} color={c} strokeWidth={2} />,
    Info: ({ s = 20, c = "currentColor" }) => <Info size={s} color={c} strokeWidth={2} />,
    Help: ({ s = 20, c = "currentColor" }) => <HelpCircle size={s} color={c} strokeWidth={2} />,
    Check: ({ s = 20, c = "currentColor" }) => <Check size={s} color={c} strokeWidth={2} />,
    CheckCircle: ({ s = 20, c = "currentColor" }) => <CheckCircle size={s} color={c} strokeWidth={2} />,
    Plus: ({ s = 20, c = "currentColor" }) => <Plus size={s} color={c} strokeWidth={2} />,
    Minus: ({ s = 20, c = "currentColor" }) => <Minus size={s} color={c} strokeWidth={2} />,
    Calendar: ({ s = 20, c = "currentColor" }) => <Calendar size={s} color={c} strokeWidth={2} />,
    CalendarDays: ({ s = 20, c = "currentColor" }) => <CalendarDays size={s} color={c} strokeWidth={2} />,
    Eye: ({ s = 20, c = "currentColor" }) => <Eye size={s} color={c} strokeWidth={2} />,
    EyeOff: ({ s = 20, c = "currentColor" }) => <EyeOff size={s} color={c} strokeWidth={2} />,
    Filter: ({ s = 20, c = "currentColor" }) => <FilterIconLucide size={s} color={c} strokeWidth={2} />,
    Sliders: ({ s = 20, c = "currentColor" }) => <SlidersHorizontal size={s} color={c} strokeWidth={2} />,
    Refresh: ({ s = 20, c = "currentColor" }) => <RefreshCw size={s} color={c} strokeWidth={2} />,
    Loader: ({ s = 20, c = "currentColor" }) => <Loader2 size={s} color={c} strokeWidth={2} />,
    Print: ({ s = 20, c = "currentColor" }) => <Printer size={s} color={c} strokeWidth={2} />,
    Download: ({ s = 20, c = "currentColor" }) => <Download size={s} color={c} strokeWidth={2} />,
    Upload: ({ s = 20, c = "currentColor" }) => <Upload size={s} color={c} strokeWidth={2} />,
    FileText: ({ s = 20, c = "currentColor" }) => <FileText size={s} color={c} strokeWidth={2} />,
    Pill: ({ s = 20, c = "currentColor" }) => <Pill size={s} color={c} strokeWidth={2} />,
    ShoppingBag: ({ s = 20, c = "currentColor" }) => <ShoppingBag size={s} color={c} strokeWidth={2} />,
    Clock: ({ s = 20, c = "currentColor" }) => <Clock size={s} color={c} strokeWidth={2} />,
    ArrowUpDown: ({ s = 20, c = "currentColor" }) => <ArrowUpDown size={s} color={c} strokeWidth={2} />,
    ArrowUp: ({ s = 20, c = "currentColor" }) => <ArrowUp size={s} color={c} strokeWidth={2} />,
    ArrowDown: ({ s = 20, c = "currentColor" }) => <ArrowDown size={s} color={c} strokeWidth={2} />,
    Dog: ({ s = 20, c = "currentColor" }) => <Dog size={s} color={c} strokeWidth={2} />,
    Cat: ({ s = 20, c = "currentColor" }) => <Cat size={s} color={c} strokeWidth={2} />,
    Bone: ({ s = 20, c = "currentColor" }) => <Bone size={s} color={c} strokeWidth={2} />,
    Paw: ({ s = 20, c = "currentColor" }) => <PawPrint size={s} color={c} strokeWidth={2} />,
    Box: ({ s = 20, c = "currentColor" }) => <Box size={s} color={c} strokeWidth={2} />,
    Frown: ({ s = 20, c = "currentColor" }) => <Frown size={s} color={c} strokeWidth={2} />,
};
