# Generated by Django 6.0.3 on 2026-04-15 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_created_at_appointment_created_by_and_more'),
        ('organizations', '0003_organization_tax_rate'),
        ('patients', '0005_owner_created_at_owner_created_by_owner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='appointment_end_after_start'),
        ),
    ]
