# Generated by Django 6.0.3 on 2026-04-15 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_appointment_end_after_start'),
        ('organizations', '0003_organization_tax_rate'),
        ('patients', '0005_owner_created_at_owner_created_by_owner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'date', 'status'], name='appointment_organiz_abc1ec_idx'),
        ),
    ]
