# Generated by Django 6.0.3 on 2026-04-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_appointment_organiz_abc1ec_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programada'), ('confirmed', 'Confirmada'), ('in_progress', 'En consulta'), ('done', 'Completada'), ('canceled', 'Cancelada'), ('no_show', 'No se presentó')], default='scheduled', max_length=20),
        ),
    ]
