# Generated by Django 6.0.3 on 2026-05-09 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_walk_in'),
        ('organizations', '0005_organizationsettings'),
        ('patients', '0010_unique_generic_pet_per_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'start_datetime', 'status'], name='idx_appt_org_start_status'),
        ),
    ]
