# Generated by Django 6.0.3 on 2026-04-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN_SAAS', 'Admin SaaS'), ('ADMIN', 'Administrador'), ('VET', 'Veterinario'), ('ASSISTANT', 'Asistente')], default='ASSISTANT', max_length=15),
        ),
    ]
