# Generated by Django 6.0.3 on 2026-04-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0003_organization_tax_rate'),
        ('users', '0004_seed_more_test_data'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'role', 'is_active'], name='users_user_organiz_5da7d7_idx'),
        ),
    ]
