# Generated by Django 6.0.3 on 2026-05-17 19:32
#
# PR-4B — Issue #11 / ADR p15+p16 (cascade lockdown día 4).
# Cambio: User.organization.on_delete CASCADE → PROTECT.
# Razón: borrar una Organization no debe eliminar silenciosamente todos sus
# usuarios. Pre-beta hardening — preservar trazabilidad, audit trails y
# satisfacer retención NOM-024 (datos del prestador de servicio).
#
# Safety:
# - Metadata-only desde la perspectiva de Postgres FK constraint (Django
#   reescribe el CONSTRAINT con la nueva cláusula ON DELETE). Lock corto.
# - null=True permanece — deuda B7 (migrar a null=False con backfill 'Vet Care
#   Internal' para legacy rows) documentada en docs/deuda/.
# - Reversible: revert sin pérdida de datos (PROTECT bloquea borrados; no
#   destruye registros).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_sync_org_settings_data'),
        ('users', '0005_user_users_user_organiz_5da7d7_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
    ]
