# Generated by Django 6.0.3 on 2026-04-05 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('medical_records', '0003_alter_medicalrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('consultation', 'Consulta médica'), ('direct_sale', 'Venta directa')], default='consultation', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='medical_records.medicalrecord'),
        ),
    ]
