# Generated by Django 6.0.3 on 2026-04-14 16:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoiceitem_presentation_alter_invoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto fijo')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto o porcentaje del descuento. 0 = sin descuento.', max_digits=10),
        ),
    ]
