# Generated by Django 6.0.3 on 2026-04-15 — editada para 3-step organization

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def populate_invoiceitem_organization(apps, schema_editor):
    """Copia organization_id de Invoice a cada InvoiceItem."""
    InvoiceItem = apps.get_model('billing', 'InvoiceItem')
    for item in InvoiceItem.objects.select_related('invoice').filter(organization__isnull=True):
        item.organization = item.invoice.organization
        item.save(update_fields=['organization'])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoiceitem_discount'),
        ('inventory', '0010_stockmovement_invoice'),
        ('organizations', '0003_organization_tax_rate'),
        ('patients', '0004_pet_birth_date_pet_color_pet_sex_alter_pet_breed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # --- Invoice ---
        migrations.AddField(
            model_name='invoice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='patients.owner'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='patients.pet'),
        ),

        # --- Service ---
        migrations.AddField(
            model_name='service',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='organizations.organization'),
        ),

        # --- InvoiceItem: campos de auditoría y soft delete ---
        migrations.AddField(
            model_name='invoiceitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),

        # --- InvoiceItem.organization: 3-step (nullable → poblar → non-null) ---
        migrations.AddField(
            model_name='invoiceitem',
            name='organization',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_set',
                to='organizations.organization',
            ),
        ),
        migrations.RunPython(
            populate_invoiceitem_organization,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_set',
                to='organizations.organization',
            ),
        ),

        # --- Índice ---
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['organization', 'created_at'], name='billing_inv_organiz_6da732_idx'),
        ),
    ]
