# Generated by Django 6.0.3 on 2026-04-15
# NOTA: XOR constraint (invoiceitem_exactly_one_source) se aplica en 0008
# después de eliminar el campo legacy 'product' y migrar los datos.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_appointment_end_after_start'),
        ('billing', '0006_invoice_is_active_invoice_updated_by_and_more'),
        ('inventory', '0011_medicalrecordproduct_created_at_and_more'),
        ('medical_records', '0004_medicalrecord_created_by_medicalrecord_is_active_and_more'),
        ('organizations', '0003_organization_tax_rate'),
        ('patients', '0005_owner_created_at_owner_created_by_owner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoiceitem',
            name='billing_inv_organiz_6da732_idx',
        ),
        # Invoice constraints
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(
                condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 1)),
                name='invoice_tax_rate_range',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(
                condition=models.Q(('subtotal__gte', 0)),
                name='invoice_subtotal_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(
                condition=models.Q(('total__gte', models.F('subtotal'))),
                name='invoice_total_gte_subtotal',
            ),
        ),
        # InvoiceItem constraints (sin XOR — se agrega en 0008 tras eliminar product)
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(
                condition=models.Q(('quantity__gt', 0)),
                name='invoiceitem_quantity_positive',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(
                condition=models.Q(('unit_price__gte', 0)),
                name='invoiceitem_unit_price_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(
                condition=models.Q(('subtotal__gte', 0)),
                name='invoiceitem_subtotal_non_negative',
            ),
        ),
    ]
