# Generated by Django 6.0.3 on 2026-04-15 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_appointment_organiz_abc1ec_idx'),
        ('billing', '0008_remove_product_legacy_xor_constraint'),
        ('inventory', '0012_presentation_presentation_stock_non_negative_and_more'),
        ('medical_records', '0004_medicalrecord_created_by_medicalrecord_is_active_and_more'),
        ('organizations', '0003_organization_tax_rate'),
        ('patients', '0005_owner_created_at_owner_created_by_owner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoiceitem',
            name='invoiceitem_exactly_one_source',
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='billing_inv_organiz_ee28d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('service__isnull', False), ('presentation__isnull', True)), models.Q(('service__isnull', True), ('presentation__isnull', False)), _connector='OR'), name='invoiceitem_exactly_one_source'),
        ),
    ]
