# Generated by Django 6.0.3 on 2026-04-24 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_remove_invoiceitem_invoiceitem_exactly_one_source_and_more'),
        ('inventory', '0012_presentation_presentation_stock_non_negative_and_more'),
        ('medical_records', '0005_medicalrecord_medical_rec_organiz_12d8fd_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='medical_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='medical_records.medicalrecord'),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together={('invoice', 'presentation')},
        ),
    ]
