# Generated by Django 6.0.3 on 2026-04-28 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_invoice_medical_record_onetoone_invoiceitem_unique'),
        ('patients', '0007_remove_owner_patients_ow_organiz_e2fb0a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='patients.pet'),
        ),
    ]
