# Generated by Django 6.0.3 on 2026-05-02 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_add_public_id_to_exposed_models'),
        ('inventory', '0014_add_public_id_to_exposed_models'),
        ('organizations', '0005_organizationsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('invoice', 'service'), name='invoiceitem_unique_invoice_service'),
        ),
    ]
