# Generated by Django 6.0.3 on 2026-05-03 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_unique_invoice_service'),
        ('organizations', '0005_organizationsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gt', 0)), name='service_base_price_positive'),
        ),
    ]
