# Generated by Django 6.0.3 on 2026-05-09 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_appointment_idx_appt_org_start_status'),
        ('billing', '0017_invoice_anchor_backfill_and_constraints'),
        ('medical_records', '0015_medicalrecord_closed_at_provenance'),
        ('organizations', '0005_organizationsettings'),
        ('patients', '0010_unique_generic_pet_per_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status', 'paid_at'], name='idx_inv_org_status_paid'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status', 'confirmed_at'], name='idx_inv_org_status_conf'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status', 'cancelled_at'], name='idx_inv_org_status_canc'),
        ),
    ]
