# Generated by Django 6.0.3 on 2026-04-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_pet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('male', 'Macho'), ('female', 'Hembra'), ('unknown', 'Desconocido')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
