# Generated by Django 6.0.3 on 2026-04-15 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_tax_rate'),
        ('patients', '0005_owner_created_at_owner_created_by_owner_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pet',
            name='patients_pe_organiz_ac3681_idx',
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['organization', 'owner'], name='patients_pe_organiz_18952a_idx'),
        ),
    ]
