# Generated by Django 6.0.3 on 2026-04-28 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationsettings'),
        ('patients', '0006_remove_pet_patients_pe_organiz_ac3681_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='owner',
            name='patients_ow_organiz_e2fb0a_idx',
        ),
        migrations.AddField(
            model_name='owner',
            name='is_generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.UniqueConstraint(condition=models.Q(('is_generic', True)), fields=('organization',), name='unique_generic_owner_per_organization'),
        ),
    ]
