# Generated by Django 6.0.3 on 2026-04-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_owner_patients_ow_organiz_e2fb0a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_generic',
            field=models.BooleanField(default=False),
        ),
    ]
