# Generated by Django 6.0.3 on 2026-05-17 19:32
#
# PR-4B — Issue #11 / ADR p15+p16 (cascade lockdown día 4).
# Cambio: Pet.owner.on_delete CASCADE → PROTECT.
# Razón: borrar un Owner cascadeaba transitivamente todos sus Pets y, vía
# MedicalRecord.pet (también CASCADE), todo su historial clínico. Violación
# directa NOM-046-ZOO-1995 §6.7 (retención mínima 5 años de expediente
# clínico veterinario). PROTECT obliga al cliente a archivar (soft-delete
# via is_active, futura A5) en lugar de destruir.
#
# Safety:
# - Generic owner (is_generic=True, walk-in) NUNCA debe borrarse —
#   protegido adicionalmente por guard en OwnerViewSet.destroy (PR-4B D5).
# - Metadata-only desde Postgres. Lock breve.
# - Reversible.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_unique_generic_pet_per_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='patients.owner'),
        ),
    ]
