# Generated by Django 6.0.3 on 2026-04-15 — editada para 3-step organization

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def populate_prescriptionitem_organization(apps, schema_editor):
    """Copia organization_id de Prescription a cada PrescriptionItem."""
    PrescriptionItem = apps.get_model('prescriptions', 'PrescriptionItem')
    for item in PrescriptionItem.objects.select_related('prescription').filter(organization__isnull=True):
        item.organization = item.prescription.organization
        item.save(update_fields=['organization'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_medicalrecordproduct_created_at_and_more'),
        ('organizations', '0003_organization_tax_rate'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # --- Prescription ---
        migrations.AddField(
            model_name='prescription',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='veterinarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL),
        ),

        # --- PrescriptionItem: auditoría y soft delete ---
        migrations.AddField(
            model_name='prescriptionitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),

        # --- PrescriptionItem.organization: 3-step ---
        migrations.AddField(
            model_name='prescriptionitem',
            name='organization',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_set',
                to='organizations.organization',
            ),
        ),
        migrations.RunPython(
            populate_prescriptionitem_organization,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_set',
                to='organizations.organization',
            ),
        ),

        # --- Indice ---
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['organization', 'created_at'], name='prescriptio_organiz_e427c3_idx'),
        ),
    ]
