# Generated by Django 6.0.3 on 2026-04-15 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_presentation_presentation_stock_non_negative_and_more'),
        ('organizations', '0003_organization_tax_rate'),
        ('prescriptions', '0002_prescription_created_by_prescription_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='prescriptionitem',
            name='prescriptio_organiz_e427c3_idx',
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='prescriptionitem_quantity_positive'),
        ),
    ]
