# Generated by Django 6.0.3 on 2026-05-09 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0016_rename_medical_rec_medical_9efa5c_idx_medical_rec_medical_a94e83_idx_and_more'),
        ('organizations', '0005_organizationsettings'),
        ('patients', '0010_unique_generic_pet_per_organization'),
        ('prescriptions', '0004_add_public_id_to_exposed_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['organization', '-created_at'], name='idx_presc_org_created'),
        ),
    ]
