# Generated by Django 6.0.3 on 2026-05-17 19:32
#
# PR-4B — Issue #11 / ADR p15+p16 (cascade lockdown día 4).
# Cambio: Prescription.pet on_delete CASCADE → PROTECT.
# Razón (incorporada al scope post-review de database-architect): la receta
# es documento legal entregado al paciente — debe sobrevivir al borrado del
# Pet (mismo argumento NOM-046 que VaccineRecord.pet). Mantener CASCADE
# generaba inconsistencia visible: vacunas protegidas, recetas destruidas.
#
# Decisión paralela diferida a Fase 2 (deuda):
# - Prescription.medical_record sigue CASCADE — debería migrar a SET_NULL +
#   snapshot (análogo a Invoice.medical_record). No incluido en PR-4B.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_pet_owner'),
        ('prescriptions', '0005_prescription_idx_presc_org_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.pet'),
        ),
    ]
