# Generated by Django 6.0.3 on 2026-04-14 16:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Tasa de IVA aplicada automáticamente a nuevos cobros (ej: 0.16 = 16%)', max_digits=5),
        ),
    ]
