# Generated by Django 6.0.3 on 2026-04-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='America/Mexico_City', max_length=64),
        ),
    ]
