# Generated by Django 6.0.3 on 2026-04-28 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_org_default_timezone_mexico'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_create_medical_record', models.BooleanField(default=True)),
                ('auto_create_invoice_on_done', models.BooleanField(default=True)),
                ('require_confirmation_before_start', models.BooleanField(default=False)),
                ('allow_anonymous_walkin', models.BooleanField(default=False)),
                ('show_status_change_history', models.BooleanField(default=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization')),
            ],
        ),
    ]
