# Generated by Django 6.0.3 on 2026-05-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsettings',
            name='auto_create_invoice_on_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='auto_create_medical_record',
            field=models.BooleanField(default=False),
        ),
    ]
